//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;
namespace MvcApplication1.Models
{
    //using System;
    //using System.Collections.Generic;
    [Table("Count")]
    public class Count
    {
        [Key]
        [Column (Order=0)]
        public string Sub_PCode { get; set; }
        public Nullable<int> Reg { get; set; }
        public Nullable<int> Arr { get; set; }
        public int Total { get; set; }
        [Key]
        [Column (Order=1)]
        public int Campus_ID { get; set; }
        //[NotMapped]
        //public SelectList Sublist { get; set; }
    }
    
}
