//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema; 
namespace MvcApplication1.Models
{
    //using System;
    //using System.Collections.Generic;

    [Table("Script_count")]
    public class Script_Count
    {
        public string Dept { get; set; }
        [Key]
        public string Subcode { get; set; }
        public int PktNo { get; set; }
        public int No_of_Scripts { get; set; }
        public string Remark { get; set; }
        public string Groups { get; set; }
        public bool Entd { get; set; }
        public string Sessn { get; set; }
        public string Paper_Type { get; set; }
    }
}
